name: Backbone
version: 7.5.1
author: Firebreath15
main: me.firebreath15.backbone.main
softdepend: [TagAPI]
commands:
  bb:
    description: Backbone by Firebreath15
    usage: /bb
    permission: backbone.use
    permission-message: You don't have permission!
  backbone:
    description: Backbone by Firebreath15
    usage: /backbone
    permission: backbone.use
    permission-message: You don't have permission!
permissions:
  backbone.use:
    default: true
  backbone.setend:
    default: op
  backbone.bspawn:
    default: op
  backbone.rspawn:
    default: op
  backbone.setreload:
    default: op
  backbone.setlobby:
    default: op