name: Backbone
version: 7.6.6
author: Firebreath15
main: me.firebreath15.backbone.main
softdepend: [TagAPI]
commands:
  bb:
    description: Backbone by Firebreath15
    usage: /bb
    permission: backbone.use
    permission-message: You don't have permission!
  backbone:
    description: Backbone by Firebreath15
    usage: /backbone
    permission: backbone.use
    permission-message: You don't have permission!
permissions:
  backbone.player:
    default: true
    children:
      backbone.use: true
      backbone.store: true
      backbone.join: true
      backbone.leave: true
  backbone.admin:
    default: op
    children:
      backbone.bspawn: true
      backbone.rspawn: true
      backbone.setlobby: true
      backbone.setreload: true
      backbone.setend: true
      backbone.sign: true
      backbone.player: true