name: Backbone
version: 7.3.7
main: me.firebreath15.backbone.main
commands:
  bb:
    description: Backbone
    usage: /bb
    permission: backbone.use
    permission-message: No Permission!
permissions:
  backbone.use:
    default: false
  backbone.store:
    default: false
  backbone.rspawn:
    default: false
  backbone.bspawn:
    default: false
  backbone.setreload:
    default: false
  backbone.setend:
    default: false
  backbone.place:
    default: false
  backbone.break:
    default: false
  backbone.sign:
    default: false
  backbone.player:
    default: op
    children:
      backbone.use: true
      backbone.store: true
  backbone.admin:
    default: op
    children:
      backbone.use: true
      backbone.store: true
      backbone.rspawn: true
      backbone.bspawn: true
      backbone.setreload: true
      backbone.setend: true
      backbone.place: true
      backbone.break: true
      backbone.sign: true